### find posts
GET http://localhost:5011/api/v1/posts HTTP/1.1



### find post by id
GET http://localhost:5011/api/v1/posts/670944e0796d9a09de873644 HTTP/1.1


#user3: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTI2YWE3ZDFjMTc2NDM3MDQ0NGY1YyIsImVtYWlsIjoidXNlcjNAbWFpbC5jb20iLCJ1c2VybmFtZSI6InVzZXIzIiwiaWF0IjoxNzI5MjYwMjQ0LCJleHAiOjE3MjkyNjM4NDR9.haGqT0yYnVZbxk_sIWlQ-oec_ANKd1T3JxWJC96YSXc
#guess: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTI2OWU2ZDFjMTc2NDM3MDQ0NGY1MiIsImVtYWlsIjoiZ3Vlc3NAbWFpbC5jb20iLCJ1c2VybmFtZSI6Imd1ZXNzIiwiaWF0IjoxNzI5MjYwMzUxLCJleHAiOjE3MjkyNjM5NTF9.jIwPBMoaIfzU1UabkLxQyRgzxLckzWGy_oEQ-bCqd4o

### create post admin: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTExZGRhMGU4ODgzNmVjMDI2ZTA3ZSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzI5MjU1NjI0LCJleHAiOjE3MjkyNTkyMjR9.VLWifyq-d15T7ipX9jhOS4D-Pvep1TZzeeyI0XduxPM
POST http://localhost:5011/api/v1/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTI2YWE3ZDFjMTc2NDM3MDQ0NGY1YyIsImVtYWlsIjoidXNlcjNAbWFpbC5jb20iLCJ1c2VybmFtZSI6InVzZXIzIiwiaWF0IjoxNzI5MjYwMjQ0LCJleHAiOjE3MjkyNjM4NDR9.haGqT0yYnVZbxk_sIWlQ-oec_ANKd1T3JxWJC96YSXc

{
    "title": "Post de Guess",
    "description": "Post description",
    "content": "this Guess can post anything"
}




### update post
PUT http://localhost:5011/api/v1/posts/670944e0796d9a09de873644 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTExZGRhMGU4ODgzNmVjMDI2ZTA3ZSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzI5MTg3Mzg5LCJleHAiOjE3MjkxOTA5ODl9.OomnVGxoLH3Ako0JFUAScj5jkU8i_iu2DD4Lg2Yfjos

{
    "description": "Post nº 1 description "
}



### DELETE post
DELETE http://localhost:5011/api/v1/posts/670944e0796d9a09de873645 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTExZGRhMGU4ODgzNmVjMDI2ZTA3ZSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzI5MTg3Mzg5LCJleHAiOjE3MjkxOTA5ODl9.OomnVGxoLH3Ako0JFUAScj5jkU8i_iu2DD4Lg2Yfjos

{}