### find users
GET http://localhost:5011/api/v1/users HTTP/1.1




### create user
POST http://localhost:5011/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "id":"aaaa",
    "name": "George Poliovei",
    "username": "gio",
    "email": "gio@mail.com"
}