
### find users
GET http://localhost:5011/api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTI2OTNiZDFjMTc2NDM3MDQ0NGY0NSIsImlhdCI6MTcyOTUxNzkxOCwiZXhwIjoxNzI5NTIxNTE4fQ.2qG8GgbsDuncNdFoak9Wdsfjy_UhYKK35xjG5SQX-5E


### find user by id
GET http://localhost:5011/api/v1/users/6706d7020a185d209477e754 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDZkNzAyMGExODVkMjA5NDc3ZTc1NCIsImVtYWlsIjoiZ2lvQG1haWwuY29tIiwidXNlcm5hbWUiOiJnaW8iLCJpYXQiOjE3MjkwOTkwNDgsImV4cCI6MTcyOTEwMjY0OH0.KKu5wXk4x7Q96czsWogUQZ6WFIiQG1DH-FHCRv56O0A



### new user
POST http://localhost:5011/api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTExZGRhMGU4ODgzNmVjMDI2ZTA3ZSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzI5MjU1NjI0LCJleHAiOjE3MjkyNTkyMjR9.VLWifyq-d15T7ipX9jhOS4D-Pvep1TZzeeyI0XduxPM
Content-Type: application/json

{
    "name": "user",
    "username": "user",
    "email": "user@mail.com",
    "password": "lifeIsAgoodShet"
}



### new manager
POST http://localhost:5011/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTExZGRhMGU4ODgzNmVjMDI2ZTA3ZSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzI5MjU5ODE2LCJleHAiOjE3MjkyNjM0MTZ9.bwt2m3miKFSNIMz5sAgOV5M_qELn8KIGIQJ6uBO3FFk

{
    "name": "Manager",
    "username": "manager",
    "email": "manager@mail.com",
    "password": "lifeIsAgoodShet",
    "roles": ["manager"]
}


### new admin
POST http://localhost:5011/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": "admin",
    "username": "admin",
    "email": "admin@mail.com",
    "password": "lifeIsAgoodShet",
    "roles": ["admin"]
}





### new guess
POST http://localhost:5011/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTExZGRhMGU4ODgzNmVjMDI2ZTA3ZSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzI5MjU5ODE2LCJleHAiOjE3MjkyNjM0MTZ9.bwt2m3miKFSNIMz5sAgOV5M_qELn8KIGIQJ6uBO3FFk

{
    "name": "Guess",
    "username": "guess",
    "email": "guess@mail.com",
    "password": "lifeIsAgoodShet",
    "roles": ["guess"]
}


### new user with 2 roles
POST http://localhost:5011/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTExZGRhMGU4ODgzNmVjMDI2ZTA3ZSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzI5MjU5ODE2LCJleHAiOjE3MjkyNjM0MTZ9.bwt2m3miKFSNIMz5sAgOV5M_qELn8KIGIQJ6uBO3FFk

{
    "name": "User2",
    "username": "user2",
    "email": "user2@mail.com",
    "password": "lifeIsAgoodShet",
    "roles": ["user","manager"]
}



### new Guess with permission posts_write
POST http://localhost:5011/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTExZGRhMGU4ODgzNmVjMDI2ZTA3ZSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzI5MjU5ODE2LCJleHAiOjE3MjkyNjM0MTZ9.bwt2m3miKFSNIMz5sAgOV5M_qELn8KIGIQJ6uBO3FFk

{
    "name": "User3",
    "username": "user3",
    "email": "user3@mail.com",
    "password": "lifeIsAgoodShet",
    "roles": ["guess"],
    "permissions":["posts_write"]
}


### DELETE manager
DELETE http://localhost:5011/api/v1/users/67126971d1c1764370444f4a HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTExZGRhMGU4ODgzNmVjMDI2ZTA3ZSIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzI5MjU5ODE2LCJleHAiOjE3MjkyNjM0MTZ9.bwt2m3miKFSNIMz5sAgOV5M_qELn8KIGIQJ6uBO3FFk

{}


